// vuejs-leaflet-demo/src/App.vue
<template>
  <div id="my-map">
    <mapbox-map v-if="useMapbox" v-bind:show-map-layer="showLayer"></mapbox-map>
    <leaflet-map v-else v-bind:show-map-layer="showLayer"></leaflet-map>
    <div id="map-control">
      <p>
        <input type="checkbox" id="checkbox-lf" v-model="showLayer">
        <label for="checkbox-lf">Show GeoJSON</label>
      </p>
      <p>
        <input type="checkbox" id="checkbox-mp" v-model="useMapbox">
        <label for="checkbox-mp">Use mapbox-gl</label>
      </p>
    </div>
  </div>
</template>

<script>
import LeafletMap from './components/LeafletMap'
import MapboxMap from './components/MapboxMap'


export default {
  name: 'app',
  components: {
    'leaflet-map': LeafletMap,
    'mapbox-map': MapboxMap
  },
  data () {
    return {
      useMapbox: false,
      showLayer: false
    }
  }
}
</script>

<style>
#map-control {
  background: white;
  position: absolute;
  z-index: 1000;
  left: 20px;
  top: 100px;
  padding: 5pt 5pt;
  box-shadow: 4px 4px 5px 2px rgba(0,0,0,0.22);
}
</style>

// react-leaflet-demo/src/App.js
import React, { Component } from 'react';
import LeafletMap from './LeafletMap.js';
import MapboxMap from './MapboxMap.js';
import './App.css';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      showLayer: false,
      showMapbox: false
    }
  }

  handleShowLayerChange = (event) => {
    this.setState({showLayer: event.target.checked});
  }

  handleMapboxChange = (event) => {
    this.setState({showMapbox: event.target.checked});
  }

  render() {
    return (
      <div>
        { this.state.showMapbox ? 
        <MapboxMap showLayer={this.state.showLayer}/>
        : <LeafletMap showLayer={this.state.showLayer}/>
        }
        <div id="control">
          <p>
            <input name="layercheckbox" type="checkbox" checked={this.state.showlayer} onChange={this.handleShowLayerChange} />
            <label htmlFor="layercheckbox">Show GeoJSON</label>
          </p>
          <p>
            <input name="mapboxcheck" type="checkbox" checked={this.state.showMapbox} onChange={this.handleMapboxChange} />
            <label htmlFor="mapboxcheck">Use Mapbox GL</label>  
          </p>  
        </div>
      </div>
    );
  }
}

export default App;
